In [1]:
# import the required libraries 
# Earth Observational (EO) data obtained from NASA Giovanni tool


In [2]:
from scipy.io import netcdf
import numpy as np
import matplotlib
import matplotlib.pyplot as pl
import netCDF4

In [3]:
#import netCDF4
#file2read = netCDF4.Dataset('Downloads/g4.timeAvgMap.M2TMNXLND_5_12_4_GWETTOP.20160501-20211031.74W_43N_73W_44N.nc','r')
#var1 = file2read.variables['var1']  # access a variable in the file

In [4]:
import netCDF4
# importing Total Precipitation data downloaded as netCDF4 data from NASA Giovanni to our notebook environment.

file2read_1 = netCDF4.Dataset('Downloads/g4.timeAvgMap.M2TMNXFLX_5_12_4_PRECTOT.20160501-20211031.180W_90S_180E_90N.nc','r')
#var1 = file2read.variables['var1']  # access a variable in the file

In [5]:
file2read_1.variables.keys()

dict_keys(['M2TMNXFLX_5_12_4_PRECTOT', 'lat', 'lat_bnds', 'lon', 'lon_bnds', 'shape_mask'])

In [6]:
# Now we import the soil moisture data downloaded as netCDF4 data from NASA Giovanni to our notebook environment.


In [7]:
import netCDF4
file2read_2 = netCDF4.Dataset('Downloads/g4.timeAvgMap.M2TMNXLND_5_12_4_GWETTOP.20160501-20211031.180W_90S_180E_90N.nc','r')
#var1 = file2read.variables['var1']  # access a variable in the file

In [8]:
file2read_2.variables.keys()

dict_keys(['M2TMNXLND_5_12_4_GWETTOP', 'lat', 'lat_bnds', 'lon', 'lon_bnds', 'shape_mask'])

In [9]:
#  Soil Temperature
# Now we import the soil temperature data downloaded as netCDF4 data from NASA Giovanni to our notebook environment.

In [10]:
import netCDF4
file2read_3 = netCDF4.Dataset('Downloads/g4.timeAvgMap.M2TMNXLND_5_12_4_TSOIL1.20160501-20211031.180W_90S_180E_90N.nc','r')
#var1 = file2read.variables['var1']  # access a variable in the file

In [11]:
file2read_3.variables.keys()

dict_keys(['M2TMNXLND_5_12_4_TSOIL1', 'lat', 'lat_bnds', 'lon', 'lon_bnds', 'shape_mask'])

In [12]:
#file2read.variables.keys()

In [13]:
#precip = file2read.variables['M2TMNXFLX_5_12_4_PRECTOT']  # access a variable in the file

In [14]:
#precip

In [12]:
# Preciipitation total
PRECTOT = file2read_1.variables['M2TMNXFLX_5_12_4_PRECTOT']  # access a variable in the file

In [13]:
# Soil Moisture
GWETTOP = file2read_2.variables['M2TMNXLND_5_12_4_GWETTOP']  # access a variable in the file

In [14]:
# Soil Temperature
TSOIL1 = file2read_3.variables['M2TMNXLND_5_12_4_TSOIL1']  # access a variable in the file

In [15]:
import numpy as np
PRECTOTvalue = PRECTOT[:]


In [16]:
PRECTOTvalue = np.ravel(PRECTOTvalue)
PRECTOTvalue = np.expand_dims(PRECTOTvalue, axis = 1)

In [17]:
import numpy as np
GWETTOPvalue = GWETTOP[:]


In [18]:
GWETTOPvalue = np.ravel(GWETTOPvalue)
GWETTOPvalue = np.expand_dims(GWETTOPvalue, axis = 1)

In [19]:
import numpy as np
TSOIL1value = TSOIL1[:]


In [20]:
TSOIL1value = np.ravel(TSOIL1value)
TSOIL1value = np.expand_dims(TSOIL1value, axis = 1)

In [21]:
import numpy as np

In [22]:
data = np.concatenate((PRECTOTvalue,GWETTOPvalue,TSOIL1value),axis=1)
# rows, and 3 coloumns

In [23]:
#data
data = np.ma.getdata(data)

In [24]:
#value
data

array([[1.e+15, 1.e+15, 1.e+15],
       [1.e+15, 1.e+15, 1.e+15],
       [1.e+15, 1.e+15, 1.e+15],
       ...,
       [1.e+15, 1.e+15, 1.e+15],
       [1.e+15, 1.e+15, 1.e+15],
       [1.e+15, 1.e+15, 1.e+15]], dtype=float32)

In [25]:

data = data[data[:,-1] < 1000]

In [26]:
print(np.shape(data))
# 261 rows means 261 data pints, two features and one target variable (label) 
# labels are: "1" and "0" 
# "1" above frosting
# "0" below frosting

(261, 3)


In [27]:
x = data[:,0:2]
y = data[:,2]

In [24]:
x

array([[1.76773192e-05, 5.10758042e-01],
       [1.91692416e-05, 3.99134606e-01],
       [2.41468169e-05, 3.86678219e-01],
       [2.70575183e-05, 6.45562351e-01],
       [1.79484014e-05, 4.44676876e-01],
       [1.97909230e-05, 4.04459953e-01],
       [2.04177395e-05, 3.69230926e-01],
       [2.34645468e-05, 3.67150068e-01],
       [1.97716618e-05, 4.56732571e-01],
       [2.21577884e-05, 4.01841551e-01],
       [2.32085076e-05, 3.36950600e-01],
       [2.44258281e-05, 3.52499843e-01],
       [1.67435301e-05, 3.90118062e-01],
       [2.02477459e-05, 4.84016180e-01],
       [2.46245709e-05, 4.92726892e-01],
       [2.68115637e-05, 5.16360581e-01],
       [2.73668393e-05, 5.88134944e-01],
       [2.62365647e-05, 6.82895064e-01],
       [1.66604077e-05, 4.73988622e-01],
       [1.91290383e-05, 5.13499796e-01],
       [2.39861693e-05, 5.05626023e-01],
       [2.81657667e-05, 5.23998320e-01],
       [2.88870724e-05, 6.01948977e-01],
       [3.04247915e-05, 7.27454305e-01],
       [3.004649

In [28]:
y

array([299.03296, 298.92065, 299.0199 , 298.51028, 299.119  , 298.91068,
       298.7218 , 298.62695, 298.88602, 298.2073 , 298.2492 , 298.04547,
       298.70038, 298.30313, 297.47998, 297.4213 , 297.62793, 297.51913,
       298.23535, 298.08704, 297.3843 , 296.97824, 297.18625, 296.8405 ,
       296.37766, 297.44757, 297.82904, 297.58304, 297.1675 , 296.5411 ,
       296.6273 , 296.39597, 296.24225, 296.1452 , 295.8209 , 296.78476,
       297.13028, 297.101  , 296.74207, 296.28168, 295.9338 , 296.047  ,
       295.85703, 295.63522, 295.3535 , 295.28748, 295.9509 , 295.63763,
       295.43076, 295.6454 , 295.2068 , 296.2219 , 296.66104, 296.0548 ,
       295.37076, 295.2348 , 295.2059 , 295.15714, 295.6931 , 295.29666,
       295.1794 , 295.08163, 295.25702, 295.22742, 295.24542, 294.31882,
       294.10037, 293.46954, 294.26303, 295.6294 , 296.30756, 295.73563,
       294.54312, 293.715  , 293.67685, 293.9142 , 294.5133 , 295.07803,
       294.81494, 294.65488, 294.56522, 294.4759 , 

In [29]:
# convertion of Temperature from Kelvin values to HOT , COLD

In [30]:
# for the simplicity, we label the temperature above 71 'F ( over 295 Kelvin) as Hot == 1
# and the values below that as Cold == 0

# 295 Kelvin is 71.33 Fahrenheit (~ 71 'F)
y = np.where(y > 295, 1, 0)

In [31]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
print(np.shape(y))

(261,)


In [35]:
OnesVal = np.where(y ==1)
print(OnesVal)

# ZeroVal = np.where(y ==0)
# print(ZeroVal)



(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        69,  70,  71,  77, 108, 129, 130]),)


In [36]:
ZeroVal = np.where(y ==0)
print(ZeroVal)


(array([ 65,  66,  67,  68,  72,  73,  74,  75,  76,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 131, 132, 133, 134, 135, 136,
       137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
       150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
       163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
       176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
       189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201,
       202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
       215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
       228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
       241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 2

In [37]:
print(np.shape(ZeroVal))

(1, 189)


In [38]:
print(np.shape(OnesVal))

(1, 72)


In [39]:
189+72

261

In [36]:
# tain and test data split
# train_features, train_labels

In [40]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels =train_test_split(x,y, test_size = 0.2, random_state = 42)
# X_train, Y_Test, y_train, Y_Test =

In [33]:
test_features

array([[2.97957740e-05, 5.35953164e-01],
       [4.29595093e-05, 6.55136108e-01],
       [1.43540401e-05, 3.63492250e-01],
       [2.60534307e-05, 5.88739455e-01],
       [2.78570533e-05, 5.41794777e-01],
       [1.57149989e-05, 3.73021334e-01],
       [2.17253655e-05, 4.28061068e-01],
       [1.26955129e-05, 2.80674100e-01],
       [2.21577884e-05, 4.01841551e-01],
       [1.49241250e-05, 3.63729209e-01],
       [3.00464908e-05, 9.49010491e-01],
       [1.22535812e-05, 3.47956866e-01],
       [3.17313097e-05, 6.24804556e-01],
       [1.80966927e-05, 3.94594908e-01],
       [1.51146278e-05, 3.65915060e-01],
       [2.40524023e-05, 4.46136355e-01],
       [3.71957576e-05, 5.98605633e-01],
       [2.04177395e-05, 3.69230926e-01],
       [3.54188087e-05, 4.78450805e-01],
       [4.37378658e-05, 6.24461651e-01],
       [3.58946054e-05, 8.22847664e-01],
       [3.98480734e-05, 6.25837564e-01],
       [1.91290383e-05, 5.13499796e-01],
       [3.82780236e-05, 6.80456281e-01],
       [1.866898

In [41]:
# scaling the data 
from sklearn.preprocessing import StandardScaler
# Scale data


scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)



In [35]:
test_features

array([[ 3.67185920e-01,  3.08868557e-01],
       [ 1.47804785e+00,  1.10764527e+00],
       [-9.35911894e-01, -8.46982777e-01],
       [ 5.13768420e-02,  6.62647843e-01],
       [ 2.03581020e-01,  3.48019660e-01],
       [-8.21063280e-01, -7.83117831e-01],
       [-3.13860148e-01, -4.14235711e-01],
       [-1.07587183e+00, -1.40203881e+00],
       [-2.77368814e-01, -5.89961708e-01],
       [-8.87803555e-01, -8.45394671e-01],
       [ 3.88343424e-01,  3.07722259e+00],
       [-1.11316550e+00, -9.51102555e-01],
       [ 5.30521989e-01,  9.04359996e-01],
       [-6.20076776e-01, -6.38529480e-01],
       [-8.71727407e-01, -8.30744863e-01],
       [-1.17486045e-01, -2.93093204e-01],
       [ 9.91656125e-01,  7.28772044e-01],
       [-4.24208134e-01, -8.08521569e-01],
       [ 8.41702819e-01, -7.65183419e-02],
       [ 1.54373181e+00,  9.02061820e-01],
       [ 8.81854415e-01,  2.23166585e+00],
       [ 1.21547985e+00,  9.11283314e-01],
       [-5.32959104e-01,  1.58383712e-01],
       [ 1.

In [42]:
# Classical Machine Learning: SVM

In [43]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [44]:
# Linear
svm_model = SVC(kernel = 'linear', C=1)
svm_model.fit(train_features, train_labels)

SVC(C=1, kernel='linear')

In [45]:
# Predict
predictions = svm_model.predict(test_features)

In [46]:
# accuaracy
accuracy = accuracy_score(test_labels,predictions)

In [40]:
print(accuracy)

0.8113207547169812


In [47]:
from sklearn.metrics import classification_report

In [48]:
# Generate classification report
report = classification_report(test_labels, predictions)

# Print the report for classical SVM Clasifier with linear kernel
print(report)

              precision    recall  f1-score   support

           0       0.82      0.95      0.88        39
           1       0.75      0.43      0.55        14

    accuracy                           0.81        53
   macro avg       0.79      0.69      0.71        53
weighted avg       0.80      0.81      0.79        53



In [ ]:
# Classical SVM Model2 with Polynomial kernel


In [49]:
# Radial Basis Function kernel (RBF) 

svm_model2 = SVC(kernel = 'rbf', C=1)
svm_model2.fit(train_features, train_labels)

SVC(C=1)

In [50]:
# Predict
predictions_rbf = svm_model2.predict(test_features)

In [51]:
# accuaracy
accuracy_rbf = accuracy_score(test_labels,predictions_rbf)

In [52]:
print(accuracy_rbf)

0.7358490566037735


In [53]:
# Generate classification report for Classical SVM with RBF kernal
report_rbf = classification_report(test_labels, predictions_rbf)

# Print the report for Classical SVM with RBF kernal
print(report_rbf)

              precision    recall  f1-score   support

           0       0.80      0.85      0.83        39
           1       0.50      0.43      0.46        14

    accuracy                           0.74        53
   macro avg       0.65      0.64      0.64        53
weighted avg       0.72      0.74      0.73        53



In [54]:
# Classical SVM model 3 with polynomial kernel

In [55]:
# Polynomial

from sklearn.svm import SVC

# Define the SVM model using a polynomial kernel
svm_model3 = SVC(kernel='poly', C=1)

# Fit the model on your training data
svm_model3.fit(train_features, train_labels)

SVC(C=1, kernel='poly')

In [56]:
# Predict
predictions_ploy = svm_model3.predict(test_features)

In [57]:
# accuaracy
accuracy_poly = accuracy_score(test_labels,predictions_ploy)

In [58]:
print(accuracy_poly)

0.8113207547169812


In [59]:
# Generate classification report for Classical SVM with Polynoomial kernel
report_poly = classification_report(test_labels, predictions_ploy)

# Print the report for Classical SVM with Polynoomial kernel
print(report_poly)

              precision    recall  f1-score   support

           0       0.80      1.00      0.89        39
           1       1.00      0.29      0.44        14

    accuracy                           0.81        53
   macro avg       0.90      0.64      0.67        53
weighted avg       0.85      0.81      0.77        53



In [60]:
# Gausian Naive Bayes model


In [61]:
from sklearn.naive_bayes import GaussianNB

# Define the Naive Bayes model
NB_model4 = GaussianNB()

# Fit the model on your training data
NB_model4.fit(train_features, train_labels)


GaussianNB()

In [62]:
# prediction
predictions_NB = NB_model4.predict(test_features)

In [63]:
# accuaracy
accuracy_NB = accuracy_score(test_labels,predictions_NB)

In [65]:
print(accuracy_NB)

0.7358490566037735


In [66]:
from sklearn.metrics import accuracy_score, classification_report

# Prediction
predictions_NB = NB_model4.predict(test_features)

# Accuracy
accuracy_NB = accuracy_score(test_labels, predictions_NB)
print(accuracy_NB)

# Generate classification report for Classical GaussianNB, handling division by zero
report_GaussianNB = classification_report(test_labels, predictions_NB, zero_division=1)

# # Print the report for Classical GaussianNB
# print(report_GaussianNB)


0.7358490566037735


In [67]:
# Print the report for Classical GaussianNB
print(report_GaussianNB)


              precision    recall  f1-score   support

           0       0.74      1.00      0.85        39
           1       1.00      0.00      0.00        14

    accuracy                           0.74        53
   macro avg       0.87      0.50      0.42        53
weighted avg       0.81      0.74      0.62        53



In [68]:
print(np.shape(test_features))

(53, 2)


In [69]:
print(np.shape(train_features))

(208, 2)
